import type {
  ConditionExpr,
  FieldDefinition,
  FieldState,
  OFSDocument,
  OpenAPIPropertyInfo,
  WhenEntry,
} from "@ofs/types";
import { isCompoundWhen } from "@ofs/types";

export interface TypeOverride {
  /** The expression to use as the yup schema factory (e.g. "string()" or "yup.string()"). */
  factory: string;
  /** Import to add to the generated file. Omit if the factory uses yup directly. */
  import?: {
    name: string;
    from: string;
  };
}

export interface GeneratorContext {
  /** Property type info for this spec's DTO fields, keyed by field name. */
  dtoProperties?: Record<string, OpenAPIPropertyInfo>;
  /** Type overrides for yup schema factories, keyed by OpenAPI type. */
  types?: Record<string, TypeOverride>;
  /** All available OpenAPI enums, keyed by schema name. */
  enums?: Record<string, string[]>;
  /** Import path for enum types (e.g. "@/api/generated/backend/index.schemas"). */
  enumImport?: string;
}

const DEFAULT_TYPE_MAP: Record<string, string> = {
  string: "yup.string()",
  number: "yup.number()",
  integer: "yup.number().integer()",
  boolean: "yup.boolean()",
};

export function generateYupCode(
  spec: OFSDocument,
  ctx: GeneratorContext = {},
): string {
  const lines: string[] = [];
  const needsHelper = specUsesContextOrCrossSection(spec);
  const customImports = collectCustomImports(ctx.types);
  const overridableFields = getOverridableFields(spec.fields);

  // Collect enum refs used by fields in this spec
  const usedEnums = collectUsedEnums(spec.fields, ctx);

  // 1. Imports
  lines.push("// This file is auto-generated by @ofs/plugin-yup. Do not edit.");
  lines.push('import * as yup from "yup";');
  for (const imp of customImports) {
    lines.push(`import { ${imp.name} } from "${imp.from}";`);
  }
  if (ctx.enumImport && usedEnums.length > 0) {
    lines.push(
      `import { ${usedEnums.join(", ")} } from "${ctx.enumImport}";`,
    );
  }
  lines.push("");

  // 2. Defaults object (types are inferred, including .oneOf() narrowing)
  const defaultsName = `${spec.section}Defaults`;
  lines.push(`export const ${defaultsName} = {`);
  for (const [name] of overridableFields) {
    const factory = resolveFieldFactory(name, ctx);
    const enumName = resolveEnumRef(name, ctx);
    if (enumName) {
      lines.push(`  ${name}: ${factory}.oneOf(Object.values(${enumName})),`);
    } else {
      lines.push(`  ${name}: ${factory},`);
    }
  }
  lines.push("};");

  // 3. Fields type — derived from defaults, preserves .oneOf() narrowing
  const fieldsTypeName = pascalCase(spec.section) + "Fields";
  lines.push(`export type ${fieldsTypeName} = typeof ${defaultsName};`);

  // 4. Schema function
  const schemaFnName = `${spec.section}Schema`;
  const exampleFields = overridableFields.slice(0, 2).map(([n]) => n);

  lines.push("");
  lines.push("/**");
  lines.push(` * Creates a validated yup schema for "${spec.section}".`);
  lines.push(" *");
  lines.push(` * Override fields with your Layer 2 content schemas — types are preserved:`);
  lines.push(" *");
  lines.push(` * const schema = ${schemaFnName}({`);
  for (const name of exampleFields) {
    lines.push(` *   ${name}: ${resolveFieldFactory(name, ctx).replace("()", "")}.oneOf([...]),`);
  }
  lines.push(` * });`);
  lines.push(" */");
  lines.push(
    `export function ${schemaFnName}<T extends Partial<${fieldsTypeName}>>(overrides?: T) {`,
  );

  // Spread defaults with overrides
  lines.push(`  const fields = { ...${defaultsName}, ...overrides };\n`);;
  lines.push("");

  // Shape
  lines.push("  return yup.object().shape({");
  emitShapeFields(spec.fields, "", "    ", lines, ctx);
  lines.push("  });");
  lines.push("}");

  // 5. getPath helper
  if (needsHelper) {
    lines.push("");
    lines.push(GET_PATH_HELPER);
  }

  lines.push("");
  return lines.join("\n");
}

// --- Type resolution ---

/**
 * Returns the OpenAPI type keys to check for overrides, in priority order.
 * For a field with type "string" and format "date", returns ["string:date", "string"].
 * For an enum $ref, returns ["string"].
 */
function resolveTypeKeys(prop: OpenAPIPropertyInfo): string[] {
  const baseType = prop.ref ? "string" : prop.type;
  if (!baseType) return [];
  if (prop.format) return [`${baseType}:${prop.format}`, baseType];
  return [baseType];
}

function resolveFieldFactory(
  fieldName: string,
  ctx: GeneratorContext,
): string {
  const prop = ctx.dtoProperties?.[fieldName];
  if (!prop) return "yup.mixed()";

  for (const key of resolveTypeKeys(prop)) {
    const override = ctx.types?.[key];
    if (override) return override.factory;
  }

  const baseType = prop.ref ? "string" : prop.type;
  return DEFAULT_TYPE_MAP[baseType ?? ""] ?? "yup.mixed()";
}

function collectCustomImports(
  types?: Record<string, TypeOverride>,
): { name: string; from: string }[] {
  if (!types) return [];
  const seen = new Set<string>();
  const imports: { name: string; from: string }[] = [];

  for (const override of Object.values(types)) {
    if (override.import) {
      const key = `${override.import.name}:${override.import.from}`;
      if (!seen.has(key)) {
        seen.add(key);
        imports.push(override.import);
      }
    }
  }

  return imports;
}

/** Returns the enum schema name if this field refs a known enum, otherwise undefined. */
function resolveEnumRef(
  fieldName: string,
  ctx: GeneratorContext,
): string | undefined {
  if (!ctx.enums || !ctx.enumImport) return undefined;
  const prop = ctx.dtoProperties?.[fieldName];
  if (!prop?.ref) return undefined;
  if (ctx.enums[prop.ref]) return prop.ref;
  return undefined;
}

/** Collects all enum names referenced by fields in this spec. */
function collectUsedEnums(
  fields: Record<string, FieldDefinition>,
  ctx: GeneratorContext,
): string[] {
  if (!ctx.enums || !ctx.enumImport) return [];
  const used = new Set<string>();

  for (const [name, field] of Object.entries(fields)) {
    const enumName = resolveEnumRef(name, ctx);
    if (enumName) used.add(enumName);
    if (field.fields) {
      for (const nested of collectUsedEnums(field.fields, ctx)) {
        used.add(nested);
      }
    }
  }

  return [...used].sort();
}

function getOverridableFields(
  fields: Record<string, FieldDefinition>,
): [string, FieldDefinition][] {
  return Object.entries(fields).filter(([, field]) => {
    if (field.fields) return false;
    if (field.state === "forbidden" && (!field.when || field.when.length === 0))
      return false;
    return true;
  });
}

// --- Shape emission ---

function emitShapeFields(
  fields: Record<string, FieldDefinition>,
  prefix: string,
  indent: string,
  lines: string[],
  ctx: GeneratorContext,
): void {
  for (const [name, field] of Object.entries(fields)) {
    const fullName = prefix ? `${prefix}.${name}` : name;

    if (field.fields) {
      emitNestedField(name, fullName, field, indent, lines, ctx);
    } else if (!field.when || field.when.length === 0) {
      emitSimpleField(name, fullName, field.state, indent, lines, prefix, ctx);
    } else if (field.when.length === 1) {
      emitSingleWhen(name, fullName, field, field.when[0], prefix, indent, lines);
    } else {
      emitMultiWhen(name, fullName, field, prefix, indent, lines);
    }
  }
}

function emitSimpleField(
  name: string,
  fullName: string,
  state: FieldState,
  indent: string,
  lines: string[],
  prefix: string,
  ctx: GeneratorContext,
): void {
  switch (state) {
    case "required":
      lines.push(`${indent}${name}: ${fieldRef(name, fullName, prefix, ctx)}.required(),`);
      break;
    case "optional":
      lines.push(`${indent}${name}: ${fieldRef(name, fullName, prefix, ctx)}.optional(),`);
      break;
    case "forbidden":
      lines.push(`${indent}${name}: yup.mixed().optional().strip(),`);
      break;
  }
}

function emitNestedField(
  name: string,
  fullName: string,
  field: FieldDefinition,
  indent: string,
  lines: string[],
  ctx: GeneratorContext,
): void {
  const innerIndent = indent + "  ";

  if (!field.when || field.when.length === 0) {
    lines.push(`${indent}${name}: yup.object().shape({`);
    emitShapeFields(field.fields!, fullName, innerIndent, lines, ctx);
    lines.push(
      `${indent}}).${field.state === "required" ? "required()" : "optional().default(undefined)"},`,
    );
  } else if (field.when.length === 1) {
    const entry = field.when[0];
    const { deps, isExpr } = buildCondition(entry, fullName);
    const depStr = formatDeps(deps);

    lines.push(`${indent}${name}: yup.object().shape({`);
    emitShapeFields(field.fields!, fullName, innerIndent, lines, ctx);
    lines.push(`${indent}}).when(${depStr}, {`);
    lines.push(`${indent}  is: ${isExpr},`);
    lines.push(`${indent}  then: ${stateCallback(entry.then)},`);
    lines.push(`${indent}  otherwise: ${nestedFallbackCallback(field.state)},`);
    lines.push(`${indent}}),`);
  } else {
    lines.push(`${indent}${name}: yup.lazy((_value, options) => {`);
    lines.push(`${indent}  const parent = options.parent;`);
    lines.push(`${indent}  const ctx = options.context;`);
    lines.push(`${indent}  const inner = yup.object().shape({`);
    emitShapeFields(field.fields!, fullName, innerIndent + "  ", lines, ctx);
    lines.push(`${indent}  });`);

    for (const entry of field.when!) {
      const condExpr = buildLazyCondition(entry, "");
      const thenExpr =
        entry.then === "forbidden"
          ? "yup.mixed().optional().strip()"
          : `inner.${entry.then === "required" ? "required()" : "optional().default(undefined)"}`;
      lines.push(`${indent}  if (${condExpr}) return ${thenExpr};`);
    }

    const baseExpr =
      field.state === "forbidden"
        ? "yup.mixed().optional().strip()"
        : `inner.${field.state === "required" ? "required()" : "optional().default(undefined)"}`;
    lines.push(`${indent}  return ${baseExpr};`);
    lines.push(`${indent}}),`);
  }
}

function emitSingleWhen(
  name: string,
  fullName: string,
  field: FieldDefinition,
  entry: WhenEntry,
  prefix: string,
  indent: string,
  lines: string[],
): void {
  const { deps, isExpr } = buildCondition(entry, prefix);
  const depStr = formatDeps(deps);

  lines.push(`${indent}${name}: fields.${name}.when(${depStr}, {`);
  lines.push(`${indent}  is: ${isExpr},`);
  lines.push(`${indent}  then: ${stateCallback(entry.then)},`);
  lines.push(`${indent}  otherwise: ${stateCallback(field.state)},`);
  lines.push(`${indent}}),`);
}

function emitMultiWhen(
  name: string,
  _fullName: string,
  field: FieldDefinition,
  prefix: string,
  indent: string,
  lines: string[],
): void {
  lines.push(`${indent}${name}: yup.lazy((_value, options) => {`);
  lines.push(`${indent}  const parent = options.parent;`);
  lines.push(`${indent}  const ctx = options.context;`);

  for (const entry of field.when!) {
    const condExpr = buildLazyCondition(entry, prefix);
    lines.push(
      `${indent}  if (${condExpr}) return fields.${name}.${entry.then === "required" ? "required()" : "optional()"};`,
    );
  }

  const baseExpr =
    field.state === "forbidden"
      ? "yup.mixed().optional().strip()"
      : `fields.${name}.${field.state === "required" ? "required()" : "optional()"}`;
  lines.push(`${indent}  return ${baseExpr};`);
  lines.push(`${indent}}),`);
}

/** Returns the expression to reference a field value — `fields.name` for top-level, direct factory for nested. */
function fieldRef(
  name: string,
  fullName: string,
  prefix: string,
  ctx: GeneratorContext,
): string {
  if (prefix) {
    // Nested field — use direct factory call (not in the spread)
    return resolveFieldFactory(fullName, ctx);
  }
  return `fields.${name}`;
}

// --- Condition building ---

interface BuiltCondition {
  deps: string[];
  isExpr: string;
}

function formatDeps(deps: string[]): string {
  return deps.length === 1
    ? `"${deps[0]}"`
    : `[${deps.map((d) => `"${d}"`).join(", ")}]`;
}

function buildCondition(entry: WhenEntry, prefix: string): BuiltCondition {
  if (isCompoundWhen(entry)) {
    const deps = collectDeps(entry.all, prefix);
    const params = buildParams(deps);
    const checks = entry.all
      .map((c) => conditionCheck(c, deps, prefix))
      .join(" &&\n      ");
    return { deps, isExpr: `(${params}) =>\n      ${checks}` };
  }

  const deps = collectDeps([entry], prefix);
  const params = buildParams(deps);
  const check = conditionCheck(entry, deps, prefix);
  return { deps, isExpr: `(${params}) => ${check}` };
}

function buildLazyCondition(entry: WhenEntry, prefix: string): string {
  if (isCompoundWhen(entry)) {
    return entry.all.map((c) => lazyConditionCheck(c, prefix)).join(" && ");
  }
  return lazyConditionCheck(entry, prefix);
}

function conditionCheck(
  cond: ConditionExpr,
  deps: string[],
  prefix: string,
): string {
  return comparatorExpr(cond, conditionValueExpr(cond, deps, prefix));
}

function lazyConditionCheck(cond: ConditionExpr, prefix: string): string {
  return comparatorExpr(cond, lazyValueExpr(cond, prefix));
}

function conditionValueExpr(
  cond: ConditionExpr,
  deps: string[],
  prefix: string,
): string {
  if (cond.context) {
    const ctxIdx = deps.indexOf("$");
    return deps.length === 1 && deps[0] === "$"
      ? `getPath(ctx, "${cond.context}")`
      : `getPath(args_${ctxIdx}, "${cond.context}")`;
  }

  if (cond.section && cond.field) {
    const ctxIdx = deps.indexOf("$");
    return deps.length === 1 && deps[0] === "$"
      ? `getPath(ctx, "crossSections.${cond.section}.${cond.field}")`
      : `getPath(args_${ctxIdx}, "crossSections.${cond.section}.${cond.field}")`;
  }

  if (cond.field) {
    const relField = stripPrefix(cond.field, prefix);
    if (deps.length === 1) return relField;
    return `args_${deps.indexOf(relField)}`;
  }

  return "undefined";
}

function lazyValueExpr(cond: ConditionExpr, prefix: string): string {
  if (cond.context) return `getPath(ctx, "${cond.context}")`;
  if (cond.section && cond.field)
    return `getPath(ctx, "crossSections.${cond.section}.${cond.field}")`;
  if (cond.field) return `parent?.${stripPrefix(cond.field, prefix)}`;
  return "undefined";
}

function comparatorExpr(cond: ConditionExpr, valueExpr: string): string {
  if (cond.is !== undefined) return `${valueExpr} === ${formatValue(cond.is)}`;
  if (cond.isNot !== undefined)
    return `${valueExpr} !== ${formatValue(cond.isNot)}`;
  if (cond.in !== undefined) {
    const values = cond.in.map(formatValue).join(", ");
    return `[${values}].includes(${valueExpr} as string)`;
  }
  if (cond.notIn !== undefined) {
    const values = cond.notIn.map(formatValue).join(", ");
    return `![${values}].includes(${valueExpr} as string)`;
  }
  return "true";
}

// --- Dependencies ---

function collectDeps(conditions: ConditionExpr[], prefix: string): string[] {
  const fieldDeps: string[] = [];
  let needsContext = false;

  for (const cond of conditions) {
    if (cond.context || (cond.section && cond.field)) {
      needsContext = true;
    } else if (cond.field) {
      const relField = stripPrefix(cond.field, prefix);
      if (!fieldDeps.includes(relField)) fieldDeps.push(relField);
    }
  }

  return needsContext ? [...fieldDeps, "$"] : fieldDeps;
}

function buildParams(deps: string[]): string {
  if (deps.length === 1) {
    return deps[0] === "$" ? "ctx: unknown" : `${deps[0]}: unknown`;
  }
  return deps.map((_d, i) => `args_${i}: unknown`).join(", ");
}

function stripPrefix(field: string, prefix: string): string {
  if (prefix && field.startsWith(prefix + ".")) {
    return field.substring(prefix.length + 1);
  }
  return field;
}

// --- State expressions ---

function stateCallback(state: FieldState): string {
  switch (state) {
    case "required":
      return `(s: yup.Schema) => s.required()`;
    case "optional":
      return `(s: yup.Schema) => s.optional()`;
    case "forbidden":
      return `() => yup.mixed().optional().strip()`;
  }
}

function nestedFallbackCallback(state: FieldState): string {
  switch (state) {
    case "required":
      return `(s: yup.Schema) => s.required()`;
    case "optional":
      return `(s: yup.Schema) => s.optional().default(undefined)`;
    case "forbidden":
      return `() => yup.mixed().optional().strip()`;
  }
}

// --- Utilities ---

function formatValue(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(resolveEnumValue(value));
  return JSON.stringify(value);
}

/**
 * Strips enum alias prefix from values like "AccountType.BUSINESS" → "BUSINESS".
 *
 * Heuristic: if the part before the first dot starts with an uppercase letter,
 * it's treated as an enum reference. This matches the OFS convention where enum
 * aliases are PascalCase and must be declared in imports.enums.
 */
function resolveEnumValue(value: string): string {
  if (!value.includes(".")) return value;
  const dotIndex = value.indexOf(".");
  const prefix = value.substring(0, dotIndex);
  if (
    prefix[0] === prefix[0].toUpperCase() &&
    prefix[0] !== prefix[0].toLowerCase()
  ) {
    return value.substring(dotIndex + 1);
  }
  return value;
}

function specUsesContextOrCrossSection(spec: OFSDocument): boolean {
  return checkFields(spec.fields);
}

function checkFields(fields: Record<string, FieldDefinition>): boolean {
  for (const field of Object.values(fields)) {
    if (field.when) {
      for (const entry of field.when) {
        if (isCompoundWhen(entry)) {
          if (entry.all.some((c) => c.context || c.section)) return true;
        } else {
          if (entry.context || entry.section) return true;
        }
      }
    }
    if (field.fields && checkFields(field.fields)) return true;
  }
  return false;
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const GET_PATH_HELPER = `function getPath(obj: unknown, path: string): unknown {
  return path.split(".").reduce<unknown>(
    (acc, key) =>
      acc != null && typeof acc === "object"
        ? (acc as Record<string, unknown>)[key]
        : undefined,
    obj,
  );
}`;
